// AUTO-GENERATED by host/puf64_r7_emit_mapping.py. Do not edit.
// R7 final-path mapping (tag 0x81B7). Same bit convention as gen1:
//   pair j = ordered_pairs[j] = (a,b), 0 <= a < b < 64.
//   response bit j = 1 if count_a < count_b, 0 if count_a > count_b.
//   count_a == count_b is a tie: INVALID, fail-closed in operation.
//   FE vector packs LSB-first: bit j -> byte j/8, bit j%8.
localparam integer PUF64_MAP_LEN_BITS   = 264;
localparam integer PUF64_MAP_LEN_BYTES  = 33;
localparam integer PUF64_MAP_PAIR_COUNT = 264;
localparam [15:0]  PUF64_MAP_TAG        = 16'h81b7;
localparam [255:0] PUF64_MAP_DIGEST_SHA3_256 = 256'h95186338708b34c4fdb4ed653e2264592fc9321c6c381ced66d45bfe785c3aab;
localparam [255:0] PUF64_MAP_SELECTION_SHA256 = 256'hb1b2b076d7059bd95f5a2e9c6783e9fe7248bbdfc13eccda0ee66abe7d56bf5b;
// {a[5:0], b[5:0]} per pair, pair 0 at the most significant end.
localparam [3167:0] PUF64_MAP_PAIRS = 3168'h23a5fc7fd0cc128e3b1ed479af24b327053461c92f77659e6e34139f557e2aca711bf6a008e86a3d90085e57e62cc10d8ba07cbbd17b0f7a2d1f9af8452c322547339346365af7634de6f543e2a7571b3f6a918e82108f8aa2190177e532610bbbadfc07d37b0c5b78a391eb4b247027653373462459d8ef4db7b52909fe57fb313a919a3e00a1662aae2255e601f30d105dfa2fc07bb7d0f9a2b1d2c38454932cf625c5b46234ef7757be29b4319ff3ac55a86918f8220b722a5d92df00c12507abbc9bb17d0cd46de394a8af31f0532264d3659872f7a34dd6fe4359f1295a7f6ac3a01a10a23ea22665f2d732500417a37cdfdbbb043b7227946b4b8a301d4933bf671d59b8f44d829e43f575b3e3a71b16aa3e906066108835715f32e1268bc03b2faa3797d0edcb926b4985381f6c3345c7644f4bf54167b16ff8e7a7e18a39586c09a82eab720b05731935f10f17c97b8bd9ba00326dcf9528af44769381dc4af6305b277e6f17bf4234e7b352a95613aa65a1a283709720d05f14c12e3fa2fb9bc03d0e5b73639a36;
// Sorted canonical-sweep lookup: (full_pair_index[10:0], dest[7:0]).
localparam [2903:0] PUF64_MAP_SORTED_FULL = 2904'h00400c0380b02c0781d03c0801502e05d0ee1e03c87a1042204489112826c4e0b1176308618db1c63b4778f61f83f88011622e4648f937294594b31672d05b8b91732fc614c31953466b8d81b838e724e61d23aa778f01ec3f07e4fea0d43a89516a3446c8e51fa4249c94d2ca5c4ca99d3527e512a45562ad55cac95f2ca596b4d772f6624c4d8eb2865ecc5993346a2d61b0b626e4de9beb8a730e71d2ba674eea5d8bc0784f15e5bce7b4fa9f8bf47eafea034098170320ac1d84510625c4c89b1462ec648e91e240c8290921e44c8a93727a504ad9732ea684d79bd37e75cf19e93ee80502a0749a97d30a65536add5fad15a6b557cb01606c9593b49696d6db3b83716e75cfbab75af6df0be37f703616c2f8671a644c8d91f26e55cb59c339e74ceb9e74b698d5dabf586bdd83b2b65eceda1b4f6cedadb9bab7bef8df9c178a715e2dc6b9372ae67cd39cf3ae7fd13a9753ea9d57aef5eed3dabb7f8bf29e5fcffbef81f07e27c6;
localparam [2375:0] PUF64_MAP_SORTED_DEST = 2376'h7227c367e1e179830352371fab94018c42425d86072fb6c165327a2200d090462890ca601f87dbe7f5f811fefe5ea8046e041b546e782ba61f2b60b19d54eb2381912ca1336df83b2e26cf600151b116c77282894a629250e4b119bd4281e4e9f585013117dba9e1f2f978de21a85ac975a959ee750d161709a80045a0f239a4864b2141a598a742925d2076421dd84804aa16050480c1e66f6739d144b05b24ecf61a2cc265446ab89c0f173b8da7c0e174020c37135da2d833e138ba2d05c6cb74b041e03148b495a8e159305ecd38039de8f68944e2f11e87404383cb65f4770cb5c742060389a64f57834d4ab163a9c2c471a0a04930914ce86612aa60ec323055a8952db6810887409caaf45a0d54b052299080a3408899eac14b2cd0c635b99186120a890c05;
function automatic [10:0] puf64_map_sorted_full(input integer j);
    puf64_map_sorted_full = PUF64_MAP_SORTED_FULL[2904-1 - 11*j -: 11];
endfunction
function automatic [8:0] puf64_map_sorted_dest(input integer j);
    puf64_map_sorted_dest = PUF64_MAP_SORTED_DEST[2376-1 - 9*j -: 9];
endfunction
function automatic [5:0] puf64_map_pair_a(input integer j);
    puf64_map_pair_a = PUF64_MAP_PAIRS[3168-1 - 12*j -: 6];
endfunction
function automatic [5:0] puf64_map_pair_b(input integer j);
    puf64_map_pair_b = PUF64_MAP_PAIRS[3168-1 - 12*j - 6 -: 6];
endfunction
