rtl/common/generic_bram.sv
rtl/common/generic_mult.sv
rtl/common/generic_fifo.sv
rtl/common/generic_srl.sv
rtl/common/generic_blk_mem_wrapper.sv
rtl/common/generic_c_shift_ram_wrapper.sv
rtl/common/generic_dist_mem_wrapper.sv
rtl/hash_core/ADDER.v
rtl/hash_core/ALGORITHM.v
rtl/hash_core/CHI1.v
rtl/hash_core/CHI2.v
rtl/hash_core/Chi_3_Iota.v
rtl/hash_core/IOTA.v
rtl/hash_core/RC.v
rtl/hash_core/THETA1.v
rtl/hash_core/THETA2_RHO_PI.v
rtl/kyber/ref/Kyber_Server.v
rtl/kyber/ref/Kyber_Client.v
rtl/kyber/ref/NTT_core_Server.v
rtl/kyber/ref/NTT_core_Client.v
rtl/kyber/ref/butterfly_Server.v
rtl/kyber/ref/butterfly_Client.v
rtl/kyber/ref/hash_core_Server.v
rtl/kyber/ref/hash_core_Client.v
rtl/kyber/ref/sha3_shake_core.v
rtl/kyber/ref/keccak_f1600_server.v
rtl/kyber/ref/keccak_f1600_client.v
rtl/kyber/ref/encode_Server.v
rtl/kyber/ref/encode_Client.v
rtl/kyber/ref/decode_Server.v
rtl/kyber/ref/decode_Client.v
rtl/kyber/ref/decode_keccak.v
rtl/kyber/ref/fifo_wrappers.v
rtl/kyber/ref/LUT.v
rtl/kyber/ref/mux4to2.v
rtl/kyber/ref/pattern.v
rtl/kyber/ref/reduc.v
rtl/kyber/kyber_axi_wrapper.v
rtl/fuzzy_extractor/bch_blank_ecc.v
rtl/fuzzy_extractor/bch_chien.v
rtl/fuzzy_extractor/bch_encode.v
rtl/fuzzy_extractor/bch_error_tmec.v
rtl/fuzzy_extractor/bch_math.v
rtl/fuzzy_extractor/bch_sigma_bma_serial.v
rtl/fuzzy_extractor/bch_syndrome.v
rtl/fuzzy_extractor/bch_syndrome_method1.v
rtl/fuzzy_extractor/bch_syndrome_method2.v
rtl/fuzzy_extractor/buff.v
rtl/fuzzy_extractor/compare_cla.v
rtl/fuzzy_extractor/fifo.v
rtl/fuzzy_extractor/matrix.v
rtl/fuzzy_extractor/util.v
rtl/fuzzy_extractor/xilinx_decoder.v
rtl/fuzzy_extractor/xilinx_encode.v
rtl/fuzzy_extractor/fuzzy_extractor.sv
rtl/puf/kp_ro_cell.sv
rtl/puf/kp_ro_cell_asic.sv
rtl/asic/reset_sync_n.sv
rtl/asic/kp_asic_ro_macro_blackbox.sv
rtl/puf/kp_puf_cells.sv
rtl/puf/kp_puf_control.sv
rtl/puf/kp_puf_top.sv
rtl/puf/uart_rx.v
rtl/puf/uart_tx.v
rtl/soc/picorv32.v
rtl/soc/soc_bram.v
rtl/soc/soc_peripherals.sv
rtl/soc/riscv_soc.sv
rtl/top/kdf_keccak.sv
rtl/top/Kyber_System_Asic_Top.sv
