#!/usr/bin/env python3
"""Generate the per-device KCV anchor ROM include.

The KCV is a public verifier, not a secret; the generated file is still
device-specific evidence and should stay private unless the KCV is explicitly
treated as non-identifying.  The tracked default is fail-closed.

Usage:
    python3 host/puf64_provision_kcv_anchor.py --kcv-hex <56 hex chars> --emit
    python3 host/puf64_provision_kcv_anchor.py --check
"""

import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "rtl" / "top" / "edge_kcv_anchor_rom.vh"
KCV_BYTES = 28
KCV_BITS = 224

HEADER = """// Device KCV anchor ROM template (tracked default = fail-closed).
//
// Generated by host/puf64_provision_kcv_anchor.py.  The KCV is a public
// verifier, not a secret; keep this artifact private if the KCV is treated as
// a device identifier.
localparam [223:0] EDGE_KCV_ROM_REF   = 224'h%s;
localparam         EDGE_KCV_ROM_VALID = 1'b1;
"""

TEMPLATE = """// Device KCV anchor ROM template (tracked default = fail-closed).
//
// The KCV is a public verifier, not a secret.  A per-device provisioning run
// (host/puf64_provision_kcv_anchor.py --emit) replaces this file locally with
// the 224-bit KCV captured from the diagnostic enrollment of the exact
// physical PUF implementation.  That generated file is device-specific; do not
// commit it to a public repository if the KCV is treated as a device
// identifier.
//
// Default: ROM_VALID=0 -> every reconstruction fails closed.
localparam [223:0] EDGE_KCV_ROM_REF   = 224'h0;
localparam         EDGE_KCV_ROM_VALID = 1'b0;
"""


def parse_kcv(text):
    cleaned = re.sub(r"[^0-9a-fA-F]", "", text)
    if len(cleaned) != KCV_BYTES * 2:
        raise ValueError(
            f"KCV must be {KCV_BYTES * 2} hex chars (224 bit), got {len(cleaned)}")
    return cleaned.lower()


def emit(kcv_hex, out_path=OUT):
    value = parse_kcv(kcv_hex)
    Path(out_path).write_text(HEADER % value)
    print(json.dumps({
        "status": "PROVISIONED",
        "output": str(out_path),
        "kcv_bits": KCV_BITS,
        "kcv_sha256": hashlib.sha256(bytes.fromhex(value)).hexdigest(),
    }, indent=2))
    return 0


def check(out_path=OUT):
    current = Path(out_path).read_text()
    if current == TEMPLATE:
        print("puf64_kcv_anchor_rom: fail-closed template in place")
        return 0
    print("puf64_kcv_anchor_rom: device-provisioned anchor present", file=sys.stderr)
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kcv-hex", default=None)
    parser.add_argument("--out", default=str(OUT))
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if args.emit:
        if not args.kcv_hex:
            parser.error("--emit requires --kcv-hex")
        try:
            return emit(args.kcv_hex, args.out)
        except ValueError as error:
            print(f"ERROR: {error}", file=sys.stderr)
            return 2
    if args.check:
        return check(args.out)
    parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
