#!/usr/bin/env python3
"""R7 mapping emitter: candidate mapping -> RTL .vh + manifest (tag 0x81B7).

Same audited bit convention as the V2 generator (pair order, LSB-first FE
packing, sorted canonical-sweep lookup), but writes the parallel R7
directory so gen1 artifacts stay untouched. Status is HOLDOUT_QUALIFIED
(holdout 801-810: 500/500 frames, 0 selected errors); release cutover is a
separate decision tracked in docs/PUF64_R7_FINALCHAR_2026-09-29.md.
"""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CAMPAIGN = ROOT / "reports/puf64_finalchar_campaign"
CANDIDATE = CAMPAIGN / "r7_mapping_candidate.json"
OUT_DIR = ROOT / "rtl/puf/v2_mapping_r7"
OUT_VH = OUT_DIR / "puf64_mapping_data.vh"
OUT_MANIFEST = ROOT / "constraints/puf64_r7_mapping_manifest.json"
OUT_FW = ROOT / "firmware/puf64_mapping_r7_data.h"
OUT_HOST = ROOT / "host/puf64_mapping_r7_generated.py"

TAG = 0x81B7
LEN_BITS = 264
LEN_BYTES = 33
PAIR_COUNT = 264
NUM_RO = 64


def canonical_index(pair):
    a, b = pair
    if a > b:
        a, b = b, a
    return a * (127 - a) // 2 + (b - a - 1)


def main() -> int:
    cand = json.loads(CANDIDATE.read_text())
    pairs = cand["pairs"]
    assert len(pairs) == PAIR_COUNT
    assert all(0 <= a < b < NUM_RO for a, b in pairs)
    assert len({tuple(p) for p in pairs}) == PAIR_COUNT
    selection = cand["selection_sha256"]
    digest = hashlib.sha3_256(json.dumps(
        pairs, sort_keys=True, separators=(",", ":")).encode()).hexdigest()

    packed = 0
    for a, b in pairs:
        packed = (packed << 12) | ((a & 0x3F) << 6) | (b & 0x3F)
    lookup = sorted([[canonical_index(p), j] for j, p in enumerate(pairs)])
    full_bits = dest_bits = 0
    for full, dest in lookup:
        full_bits = (full_bits << 11) | (full & 0x7FF)
        dest_bits = (dest_bits << 9) | (dest & 0x1FF)

    manifest = {
        "schema": "r7-mapping-manifest-v1",
        "mapping_tag": TAG,
        "mapping_tag_hex": f"0x{TAG:04x}",
        "mapping_length_bits": LEN_BITS,
        "mapping_length_bytes": LEN_BYTES,
        "selected_pair_count": PAIR_COUNT,
        "pairs": pairs,
        "full_mapping_digest_sha3_256": digest,
        "selection_sha256": selection,
        "train_freeze_sha256": cand["train_freeze_sha256"],
        "train_input": "pilot 703 + train 704-723 (final path, ZYNQ-A01)",
        "status": "R7_HOLDOUT_QUALIFIED_801_810",
    }
    vh = "\n".join([
        "// AUTO-GENERATED by host/puf64_r7_emit_mapping.py. Do not edit.",
        "// R7 final-path mapping (tag 0x81B7). Same bit convention as gen1:",
        "//   pair j = ordered_pairs[j] = (a,b), 0 <= a < b < 64.",
        "//   response bit j = 1 if count_a < count_b, 0 if count_a > count_b.",
        "//   count_a == count_b is a tie: INVALID, fail-closed in operation.",
        "//   FE vector packs LSB-first: bit j -> byte j/8, bit j%8.",
        f"localparam integer PUF64_MAP_LEN_BITS   = {LEN_BITS};",
        f"localparam integer PUF64_MAP_LEN_BYTES  = {LEN_BYTES};",
        f"localparam integer PUF64_MAP_PAIR_COUNT = {PAIR_COUNT};",
        f"localparam [15:0]  PUF64_MAP_TAG        = 16'h{TAG:04x};",
        f"localparam [255:0] PUF64_MAP_DIGEST_SHA3_256 = 256'h{digest};",
        f"localparam [255:0] PUF64_MAP_SELECTION_SHA256 = 256'h{selection};",
        "// {a[5:0], b[5:0]} per pair, pair 0 at the most significant end.",
        "localparam [3167:0] PUF64_MAP_PAIRS = 3168'h%s;"
        % ("%x" % packed).zfill(3168 // 4),
        "// Sorted canonical-sweep lookup: (full_pair_index[10:0], dest[7:0]).",
        "localparam [2903:0] PUF64_MAP_SORTED_FULL = 2904'h%s;"
        % ("%x" % full_bits).zfill(2904 // 4),
        "localparam [2375:0] PUF64_MAP_SORTED_DEST = 2376'h%s;"
        % ("%x" % dest_bits).zfill(2376 // 4),
        "function automatic [10:0] puf64_map_sorted_full(input integer j);",
        "    puf64_map_sorted_full = PUF64_MAP_SORTED_FULL[2904-1 - 11*j -: 11];",
        "endfunction",
        "function automatic [8:0] puf64_map_sorted_dest(input integer j);",
        "    puf64_map_sorted_dest = PUF64_MAP_SORTED_DEST[2376-1 - 9*j -: 9];",
        "endfunction",
        "function automatic [5:0] puf64_map_pair_a(input integer j);",
        "    puf64_map_pair_a = PUF64_MAP_PAIRS[3168-1 - 12*j -: 6];",
        "endfunction",
        "function automatic [5:0] puf64_map_pair_b(input integer j);",
        "    puf64_map_pair_b = PUF64_MAP_PAIRS[3168-1 - 12*j - 6 -: 6];",
        "endfunction",
        "",
    ])
    # Verify the tables decode back exactly (fail closed on emit bug).
    assert len(pairs) == PAIR_COUNT
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    def hex_bytes(hexstr):
        raw = bytes.fromhex(hexstr)
        return ",\n    ".join(
            ", ".join(f"0x{b:02x}" for b in raw[i:i + 8])
            for i in range(0, len(raw), 8))

    fw = "\n".join([
        "/* AUTO-GENERATED by host/puf64_r7_emit_mapping.py. Do not edit. */",
        "#ifndef PUF64_MAPPING_R7_DATA_H",
        "#define PUF64_MAPPING_R7_DATA_H",
        "",
        f"#define PUF64_MAP_LEN_BITS   {LEN_BITS}u",
        f"#define PUF64_MAP_LEN_BYTES  {LEN_BYTES}u",
        f"#define PUF64_MAP_PAIR_COUNT {PAIR_COUNT}u",
        f"#define PUF64_MAP_TAG        0x{TAG:04X}u",
        "",
        "static const unsigned char PUF64_MAP_DIGEST_SHA3_256[32] = {",
        f"    {hex_bytes(digest)}",
        "};",
        "static const unsigned char PUF64_MAP_SELECTION_SHA256[32] = {",
        f"    {hex_bytes(selection)}",
        "};",
        "",
        "#endif",
        "",
    ])
    host_py = "\n".join([
        '"""AUTO-GENERATED by host/puf64_r7_emit_mapping.py. Do not edit."""',
        "",
        'SCHEMA = "puf64-mapping-r7-v1"',
        'MAPPING_STATUS = "R7_HOLDOUT_QUALIFIED_ZYNQ_A01_FINAL_PATH"',
        f"MAPPING_TAG = 0x{TAG:04X}",
        f"MAPPING_LEN_BITS = {LEN_BITS}",
        f"MAPPING_LEN_BYTES = {LEN_BYTES}",
        f"SELECTED_PAIR_COUNT = {PAIR_COUNT}",
        f'FULL_MAPPING_DIGEST_SHA3_256 = "{digest}"',
        f'SELECTION_SHA256 = "{selection}"',
        "ORDERED_PAIRS = (",
    ] + [f"    ({a}, {b})," for a, b in pairs] + [")", ""])
    for path, payload in ((OUT_VH, vh), (OUT_MANIFEST, json.dumps(
            manifest, indent=1, sort_keys=True) + "\n"),
            (OUT_FW, fw), (OUT_HOST, host_py)):
        if path.exists():
            current = path.read_text()
            if current != payload:
                print(f"R7_EMIT_MISMATCH: {path} differs", file=sys.stderr)
                return 1
        else:
            path.write_text(payload)
    print(f"R7_EMIT_PASS tag=0x{TAG:04X} digest={digest[:12]}... "
          f"sel={selection[:12]}...")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
