// AUTO-GENERATED by host/puf64_macrov2_generate_mapping.py --emit. Do not edit.
// Mapping bit convention (frozen, audited):
//   pair j = ordered_pairs[j] = (a,b), 0 <= a < b < 64.
//   response bit j = 1 if count_a < count_b, 0 if count_a > count_b.
//   count_a == count_b is a tie: INVALID, fail-closed in operation.
//   FE vector packs LSB-first: bit j -> byte j/8, bit j%8.
localparam integer PUF64_MAP_LEN_BITS   = 264;
localparam integer PUF64_MAP_LEN_BYTES  = 33;
localparam integer PUF64_MAP_PAIR_COUNT = 264;
localparam [15:0]  PUF64_MAP_TAG        = 16'h81b5;
localparam [255:0] PUF64_MAP_DIGEST_SHA3_256 = 256'hb581f44f7c36b451e1ae4e9afc53bab7b2646ed7414ba70514f3354b88cc1ae1;
localparam [255:0] PUF64_MAP_SELECTION_SHA256 = 256'h2e37c3c11d5c02cfd0bbc21e0837f2738b24e0de9ad020f596fc1381e449d317;
// {a[5:0], b[5:0]} per pair, pair 0 at the most significant end.
localparam [3167:0] PUF64_MAP_PAIRS = 3168'h23dafa5fc0df328107c3847bb722794b49336365af7634de29b431fbf6a77353ac86906a1550221ae2e03e608d525219af75fd7fa33c0c4a301fbb784794b2264d365b36234ef29d7b16ff41ad7e3a772106c1698aa56e00b18f36009497722666b5fa7fd13c0cc1f0a3b46de39252932cf65b48ef4d829e77169b43f3be9f505c86c8a916a2d502e18d3e05260b72255d9afd7fc33a1280f0e3b1edcb94522769345988f32af4dd6f17bf4356be39c86716c069aae56200f18b5203659b708865fafc0d733d13a470cbba2d1f94b8256624bf68f44f377f69e6f5290c7e06715c3a98ac86a35501482e1b708f2e59ab31923a5e81df13dc3c0fb26dd394b39384765b27a3298bf14db69d39087e9ffb35722a6e0553ea00519483708b36696b11923c1d77e8338c3debb0edcf9498464cb659d2634f4bff7b539b2be4217316ac1672e900136a3d51a20ae2205e552b7e6337670138efdb7ae7c0d29281f64568f22532b4c7363f6af77539e6e105017e8a72dcb2e3e952a57700d18882b0977e532667d111c3aefc0f9b74;
// Sorted canonical-sweep lookup: (full_pair_index[10:0], dest[7:0]).
localparam [2903:0] PUF64_MAP_SORTED_FULL = 2904'h0000100500c01c04c1082d09a1482c8640cc19c3488210a21c4488e1222a0588ba184320668d51c6398778f11f0408851192524ac9692e28051ca91542aa55cb496c2de5c4b997830c648cd9b3376724e61d23aa75cf61f33f07e506a0f42086d0e21f4588b51b23f4849392b2594b697136a724f8a1d4729252ea6d5f2cb59ab716eadf5c2b89762f75f8bf580b18646c919332f662cd1a334d6b0d79b0b62702e21cc39c74ce9dd5bb9784f15e5bce7a0f69fa3f57ecfea034098170320ec218450e61f43f88711232c718f521244c9b93d27e504ad9732f2674d09a337a6fcf19f540286511a3d48691d24a5b4ca9ad44a9756eafd69add5bebf582b25682d25aeb67706e2dcfbab75aec5eabd97b6fd5fdc0d8530b617c338af18e33c698db2ae58cb396b34e73ce99d73ce86d25a7f55ec1d97b4369ededcfbf38cf1ce3dc7f91f2ae73cef9ff41eb3d7bb3f6fee3dcfba778f07e23c5f8df29e5fcffa2f63f13e37cdfa3f5bebfdf;
localparam [2375:0] PUF64_MAP_SORTED_DEST = 2376'h6c2e874fc3d268325a7a2e0aa943b85c6c7f5e8753a3d7fb70bc242239d0403639960ca602c0d806471a1086a40c255ac372c1d9eafd3d96c76bb6d86938c25199c8ae9440983edd2f8fd42c100125d88a668a94e6a04a495c101793cdced69165ee1b4f35d410102385886311a0d323c3eaf9b2b2689d1e4344b054a6da2e071f2b91934c2272291a5d4ca23a15562803b2452a9052249cb03783c5c8e671f03c5d7d37cf2397d9b1980d560b098606f2888202108b5160c77a0080e281145629009b55e073799c122311aad9a81407141e28f568c1a07180381862231109fc9b5e1d42c982b2cdec571c25c9aeb36a35d04a059ad54bf1f27cfc545a21c4a465b9e0400140985f0b50441c4ee557a319e06822958aee49b2cd08625b2056a819920cce663415c812;
function automatic [10:0] puf64_map_sorted_full(input integer j);
    puf64_map_sorted_full = PUF64_MAP_SORTED_FULL[2904-1 - 11*j -: 11];
endfunction
function automatic [8:0] puf64_map_sorted_dest(input integer j);
    puf64_map_sorted_dest = PUF64_MAP_SORTED_DEST[2376-1 - 9*j -: 9];
endfunction
function automatic [5:0] puf64_map_pair_a(input integer j);
    puf64_map_pair_a = PUF64_MAP_PAIRS[3168-1 - 12*j -: 6];
endfunction
function automatic [5:0] puf64_map_pair_b(input integer j);
    puf64_map_pair_b = PUF64_MAP_PAIRS[3168-1 - 12*j - 6 -: 6];
endfunction
