// AUTO-GENERATED by scripts/helper_record_spec.py --emit. Do not edit.
// Synthetic helper-record KAT shared by the RTL parser and firmware
// mirror cross tests. Values are not board secrets.
// No include guard: localparams are module scoped.

localparam [607:0] HREC_KAT_RAW = {
    32'ha58eb2c8,
    32'h5bddc15a,
    32'hf3424f24,
    32'h1260dd30,
    32'hf2ad7266,
    32'h31b04b06,
    32'h2adc62fe,
    32'h549b201f,
    32'h1e1d1c1b,
    32'h1a191817,
    32'h16151413,
    32'h1211100f,
    32'h0e0d0c0b,
    32'h0a090807,
    32'h06050403,
    32'h02010000,
    32'h01000000,
    32'h01010101,
    32'h55464b52
};
localparam [607:0] HREC_KAT_RAW_ALT = {
    32'hfc3eb2c8,
    32'h5bddc15a,
    32'hf3424f24,
    32'h1260dd30,
    32'hf2ad7266,
    32'h31b04b06,
    32'h2adc62fe,
    32'h549b201f,
    32'h1e1d1c1b,
    32'h1a191817,
    32'h16151413,
    32'h1211100f,
    32'h0e0d0c0b,
    32'h0a090807,
    32'h06050403,
    32'h02010100,
    32'h01000000,
    32'h01010101,
    32'h55464b52
};
localparam [263:0] HREC_KAT_HELPER = 264'h201f1e1d1c1b1a191817161514131211100f0e0d0c0b0a09080706050403020100;
localparam [223:0] HREC_KAT_KCV    = 224'hb2c85bddc15af3424f241260dd30f2ad726631b04b062adc62fe549b;
localparam [55:0]  HREC_KAT_CTX    = 56'h01000001010101;
localparam [7:0]   HREC_KAT_GEN    = 8'h01;
localparam [7:0]   HREC_KAT_PROFILE = 8'h01;
localparam [7:0]   HREC_KAT_FE     = 8'h01;
localparam [7:0]   HREC_KAT_MAPLEN = 8'h00;
localparam [15:0]  HREC_KAT_MAPTAG = 16'h0000;
