## C2 narrow FIXED_ROUTE for each RO tap net.
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 SR1BEG3  { SR1BEG_S0 ER1BEG1 CLK1 CLBLM_M_CLK }  IMUX_L40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[0].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[0].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { FAN_ALT5 FAN_BOUNCE5 CLK1 CLBLM_M_CLK }  EL1BEG1 IMUX_L2 CLBLM_M_A2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[10].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[10].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { NN2BEG2 NE2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  NL1BEG1 NE2BEG1 IMUX2 CLBLM_M_A2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[11].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[11].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 ER1BEG3 SS2BEG3  { SR1BEG_S0 SR1BEG1 CLK0 CLBLM_L_CLK }  IMUX7 CLBLM_M_A1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[12].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[12].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { EE2BEG2 SL1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[13].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[13].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_A CLBLM_LOGIC_OUTS8  { EE2BEG0 WR1BEG1 CLK_L1 CLBLM_M_CLK }  NL1BEG_N3 IMUX14 CLBLM_L_B1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[14].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[14].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_B  { CLBLM_M_BMUX CLBLM_LOGIC_OUTS21 WR1BEG_S0 SR1BEG_S0 ER1BEG1 CLK_L1 CLBLM_M_CLK }  CLBLM_LOGIC_OUTS13 IMUX_L19 CLBLM_L_B2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[15].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[15].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 WW2BEG1 NL1BEG1 EL1BEG0 SL1BEG0  { ER1BEG1 CLK1 CLBLM_M_CLK }  BYP_ALT1 BYP_BOUNCE1 IMUX_L19 CLBLM_L_B2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[1].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[1].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C  { CLBLM_LOGIC_OUTS14 NE2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  CLBLM_M_CMUX CLBLM_LOGIC_OUTS22 IMUX_L40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[2].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[2].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22  { SR1BEG1 CLK0 CLBLM_L_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[3].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[3].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C  { CLBLM_L_CMUX CLBLM_LOGIC_OUTS18 SS6BEG0 SE2BEG0 ER1BEG1 CLK0 CLBLM_L_CLK }  CLBLM_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5 IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[4].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[4].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 SR1BEG3  { SR1BEG_S0 SL1BEG0 ER1BEG1 CLK1 CLBLM_M_CLK }  IMUX_L40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[5].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[5].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C  { CLBLM_LOGIC_OUTS10 NN2BEG2 NE2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLM_L_CLK }  CLBLM_L_CMUX CLBLM_LOGIC_OUTS18 IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[6].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[6].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C  { CLBLM_LOGIC_OUTS10 SE6BEG2 SE2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLM_L_CLK }  CLBLM_L_CMUX CLBLM_LOGIC_OUTS18 IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[7].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[7].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 SR1BEG3  { SS2BEG3 SS2BEG3 SR1BEG_S0 SR1BEG1 CLK0 CLBLM_L_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[8].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[8].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { SE6BEG2 EL1BEG1 EL1BEG0 ER1BEG1 CLK1 CLBLM_M_CLK }  FAN_ALT5 FAN_BOUNCE5 IMUX_L41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[9].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[9].counter/clk"}]
