## C2 narrow FIXED_ROUTE for each RO tap net.
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_L_CMUX CLBLM_LOGIC_OUTS18  { WW2BEG0 NN2BEG1 SR1BEG1 CLK1 CLBLM_M_CLK }  IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[0].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[0].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13  { NR1BEG1 EL1BEG0 SL1BEG0 SR1BEG1 CLK_L1 CLBLL_LL_CLK }  SE2BEG1 IMUX_L18 CLBLL_LL_B2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[10].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[10].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { WL1BEG1 NL1BEG1 NL1BEG0 WR1BEG1 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[11].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[11].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { WW2BEG2 NE6BEG3 WR1BEG_S0 WR1BEG1 CLK_L1 CLBLL_LL_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[12].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[12].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN6BEG2 SR1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[13].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[13].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { WW2BEG2 NW2BEG3 FAN_ALT5 FAN_BOUNCE5 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[14].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[14].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13  { SS2BEG1 NR1BEG1 NN2BEG1 SR1BEG1 CLK1 CLBLM_M_CLK }  SL1BEG1 IMUX18 CLBLM_M_B2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[15].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[15].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { SS2BEG2 EE2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK1 CLBLL_LL_CLK }  SR1BEG3 IMUX40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[16].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[16].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C  { CLBLL_LL_CMUX CLBLL_LOGIC_OUTS22 SW2BEG0 SR1BEG1 CLK1 CLBLL_LL_CLK }  CLBLL_LOGIC_OUTS14 SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[17].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[17].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { SL1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK1 CLBLL_LL_CLK }  SR1BEG3 IMUX40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[18].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[18].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14 SR1BEG3  { SR1BEG_S0 SE2BEG0 NN6BEG0 WR1BEG1 CLK_L1 CLBLL_LL_CLK }  IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[19].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[19].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NL1BEG1 NN2BEG1 SR1BEG1 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[1].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[1].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NE2BEG2 NE6BEG2 SL1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK1 CLBLL_LL_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[20].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[20].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { BYP_ALT2 BYP_BOUNCE2 FAN_ALT1 FAN_BOUNCE1 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  IMUX_L20 CLBLL_L_C2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[21].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[21].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { SW2BEG2 SL1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  SR1BEG3 IMUX40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[22].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[22].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13  { EL1BEG0 NR1BEG0 WR1BEG1 SR1BEG1 CLK1 CLBLL_LL_CLK }  WW2BEG1 ER1BEG2 IMUX_L14 CLBLL_L_B1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[23].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[23].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 BYP_ALT5 BYP_BOUNCE5  { FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  IMUX_L29 CLBLL_LL_C2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[24].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[24].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLL_L_CLK }  SR1BEG3 IMUX40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[25].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[25].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 SR1BEG3  { ER1BEG_S0 ER1BEG1 CLK1 CLBLL_LL_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[26].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[26].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14 NN2BEG2 FAN_ALT5 FAN_BOUNCE5  { CLK1 CLBLL_LL_CLK }  BYP_ALT5 BYP_BOUNCE5 IMUX7 CLBLL_LL_A1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[27].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[27].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 BYP_ALT4 BYP_BOUNCE4 FAN_ALT1 FAN_BOUNCE1 FAN_ALT5 FAN_BOUNCE5  { CLK1 CLBLL_LL_CLK }  FAN_ALT7 FAN_BOUNCE7 IMUX32 CLBLL_LL_C1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[28].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[28].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5  { CLK_L1 CLBLL_LL_CLK }  IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[29].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[29].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[2].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[2].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14 NW2BEG2  { BYP_ALT5 BYP_BOUNCE5 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLL_L_CLK }  IMUX_L3 CLBLL_L_A2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[30].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[30].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5  { CLK1 CLBLL_LL_CLK }  IMUX41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[31].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[31].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5  { CLK1 CLBLL_LL_CLK }  IMUX41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[32].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[32].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NW2BEG2 SR1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[33].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[33].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10  { NL1BEG1 NN2BEG1 SR1BEG1 CLK_L1 CLBLL_LL_CLK }  NN2BEG2 BYP_ALT5 BYP_BOUNCE5 IMUX_L7 CLBLL_LL_A1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[34].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[34].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 SR1BEG3  { SE2BEG3 ER1BEG_S0 SL1BEG0 SR1BEG1 CLK1 CLBLL_LL_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[35].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[35].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { ER1BEG3 ER1BEG_S0 ER1BEG1 CLK0 CLBLL_L_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[36].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[36].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 BYP_ALT5 BYP_BOUNCE5 FAN_ALT5 FAN_BOUNCE5  { CLK_L1 CLBLL_LL_CLK }  FAN_ALT7 FAN_BOUNCE7 IMUX_L32 CLBLL_LL_C1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[37].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[37].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 NN2BEG2  { FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  BYP_ALT5 BYP_BOUNCE5 IMUX_L7 CLBLL_LL_A1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[38].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[38].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C  { CLBLL_LOGIC_OUTS10 WL1BEG1 WL1BEG0 SR1BEG1 CLK1 CLBLL_LL_CLK }  CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[39].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[39].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 NL1BEG1 NW2BEG1 SR1BEG1 CLK0 CLBLM_L_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[3].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[3].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13  { BYP_ALT5 BYP_BOUNCE5 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  NR1BEG1 NL1BEG0 IMUX_L32 CLBLL_LL_C1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[40].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[40].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NL1BEG1 NW2BEG1 SR1BEG1 CLK_L1 CLBLL_LL_CLK }  SR1BEG3 IMUX40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[41].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[41].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 SS2BEG2  { FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLL_L_CLK }  NR1BEG2 NR1BEG2 IMUX36 CLBLL_L_D2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[42].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[42].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10  { SE2BEG2 NR1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLL_L_CLK }  FAN_ALT5 FAN_BOUNCE5 IMUX41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[43].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[43].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NL1BEG1 NN2BEG1 SR1BEG1 CLK_L0 CLBLL_L_CLK }  NN2BEG2 BYP_ALT2 BYP_BOUNCE2 IMUX_L6 CLBLL_L_A1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[44].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[44].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLL_L_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[45].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[45].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_L_CMUX CLBLL_LOGIC_OUTS18  { ER1BEG1 CLK0 CLBLL_L_CLK }  IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[46].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[46].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9 BYP_ALT4 BYP_BOUNCE4  { BYP_ALT5 BYP_BOUNCE5 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLL_L_CLK }  IMUX20 CLBLL_L_C2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[47].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[47].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5  { CLK1 CLBLM_M_CLK }  IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[48].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[48].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9  { NR1BEG1 EL1BEG0 SL1BEG0 SR1BEG1 CLK_L1 CLBLL_LL_CLK }  SE2BEG1 IMUX_L18 CLBLL_LL_B2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[49].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[49].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NR1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLL_L_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[4].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[4].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22  { NE2BEG0 NR1BEG0 WR1BEG1 CLK1 CLBLM_M_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[50].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[50].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C  { CLBLL_LOGIC_OUTS10 SL1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLL_L_CLK }  CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[51].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[51].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NL1BEG1 NL1BEG0 WR1BEG1 CLK0 CLBLM_L_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[52].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[52].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C  { CLBLL_LOGIC_OUTS10 NW2BEG2 NN2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[53].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[53].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22  { SL1BEG0 ER1BEG1 CLK_L0 CLBLL_L_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[54].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[54].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { SL1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[55].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[55].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { WL1BEG1 NL1BEG1 EL1BEG0 ER1BEG1 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[56].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[56].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10  { NW2BEG2 NL1BEG1 NN2BEG1 SR1BEG1 CLK0 CLBLM_L_CLK }  FAN_ALT5 FAN_BOUNCE5 IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[57].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[57].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5  { CLK1 CLBLL_LL_CLK }  IMUX41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[58].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[58].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NR1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[59].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[59].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C  { CLBLL_LOGIC_OUTS10 WL1BEG1 NL1BEG1 NL1BEG0 WR1BEG1 CLK_L1 CLBLL_LL_CLK }  CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[5].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[5].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C  { CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 NE2BEG0 WR1BEG1 CLK_L0 CLBLL_L_CLK }  CLBLL_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5 IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[60].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[60].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_L_CMUX CLBLM_LOGIC_OUTS18  { NW6BEG0 SR1BEG_S0 SR1BEG1 CLK0 CLBLM_L_CLK }  IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[61].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[61].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5  { CLK1 CLBLM_M_CLK }  IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[62].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[62].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5  { CLK_L0 CLBLL_L_CLK }  IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[63].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[63].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C  { CLBLL_LL_CMUX CLBLL_LOGIC_OUTS22 ER1BEG1 CLK0 CLBLM_L_CLK }  CLBLL_LOGIC_OUTS14 EL1BEG1 IMUX3 CLBLM_L_A2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[6].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[6].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C CLBLL_LOGIC_OUTS10  { SL1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLL_L_CLK }  FAN_ALT5 FAN_BOUNCE5 IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[7].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[7].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 SS2BEG1  { BYP_ALT5 BYP_BOUNCE5 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  IMUX19 CLBLM_L_B2 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[8].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[8].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { EE4BEG2 NR1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[9].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_core/u_bench/ro[9].counter/clk"}]
