## C2 bench LOCK_PINS for the RO LUTs.
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[0].ro_cell/u_backend/LUT6_INV0"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[0].ro_cell/u_backend/LUT6_INV1"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[0].ro_cell/u_backend/LUT6_INV2"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[0].ro_cell/u_backend/LUT6_NAND0"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[1].ro_cell/u_backend/LUT6_INV0"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[1].ro_cell/u_backend/LUT6_INV1"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[1].ro_cell/u_backend/LUT6_INV2"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[1].ro_cell/u_backend/LUT6_NAND0"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[2].ro_cell/u_backend/LUT6_INV0"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[2].ro_cell/u_backend/LUT6_INV1"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[2].ro_cell/u_backend/LUT6_INV2"}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[2].ro_cell/u_backend/LUT6_NAND0"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[3].ro_cell/u_backend/LUT6_INV0"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[3].ro_cell/u_backend/LUT6_INV1"}]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[3].ro_cell/u_backend/LUT6_INV2"}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A3 I3:A4 I4:A5 I5:A6} [get_cells -hierarchical -filter {NAME == "u_bench/ro[3].ro_cell/u_backend/LUT6_NAND0"}]
