## F4 narrow FIXED_ROUTE for the RO -> prescaler tap nets.
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9  { SE2BEG1 NN6BEG1 SR1BEG1 CLK1 CLBLM_M_CLK }  BYP_ALT4 BYP_BOUNCE4 IMUX_L20 CLBLM_L_C2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[0].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[0].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { SE2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  FAN_ALT5 FAN_BOUNCE5 IMUX_L41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[1].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[1].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN6BEG2 NL1BEG1 NN2BEG1 SR1BEG1 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[2].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[2].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NE6BEG2 SE2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[3].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[3].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 SR1BEG3  { WW2BEG3 NE6BEG0 EE2BEG0 ER1BEG1 CLK_L1 CLBLM_M_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[4].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[4].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { NL1BEG1 NN2BEG1 NN2BEG1 SR1BEG1 CLK0 CLBLM_L_CLK }  FAN_ALT5 FAN_BOUNCE5 IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[5].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[5].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5  { CLK1 CLBLM_M_CLK }  IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[6].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[6].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22  { NE2BEG0 EE2BEG0 WR1BEG1 CLK_L0 CLBLL_L_CLK }  IMUX_L40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[7].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[7].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9 BYP_ALT4 BYP_BOUNCE4  { BYP_ALT5 BYP_BOUNCE5 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLM_L_CLK }  IMUX_L20 CLBLM_L_C2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[8].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[8].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { NE2BEG2 NR1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  FAN_ALT5 FAN_BOUNCE5 IMUX_L41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[9].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[9].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 BYP_ALT2 BYP_BOUNCE2 FAN_ALT1 FAN_BOUNCE1 FAN_ALT5 FAN_BOUNCE5  { CLK_L1 CLBLM_M_CLK }  BYP_ALT5 BYP_BOUNCE5 IMUX_L45 CLBLM_M_D2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[10].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[10].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { ER1BEG3 ER1BEG_S0 NE2BEG0 WR1BEG1 CLK_L1 CLBLM_M_CLK }  SR1BEG3 IMUX_L40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[11].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[11].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_A CLBLM_LOGIC_OUTS12  { NN6BEG0 SR1BEG_S0 SL1BEG0 SR1BEG1 CLK_L1 CLBLM_M_CLK }  NW2BEG0 EL1BEG_N3 IMUX_L15 CLBLM_M_B1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[12].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[12].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 BYP_ALT5 BYP_BOUNCE5  { FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLM_M_CLK }  IMUX_L29 CLBLM_M_C2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[13].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[13].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9  { BYP_ALT4 BYP_BOUNCE4 BYP_ALT5 BYP_BOUNCE5 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  SL1BEG1 SS2BEG1 IMUX19 CLBLM_L_B2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[14].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[14].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NL1BEG1 NW2BEG1 SR1BEG1 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[15].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[15].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 WL1BEG1  { SW2BEG1 NL1BEG1 EL1BEG0 ER1BEG1 CLK1 CLBLM_M_CLK }  IMUX_L3 CLBLL_L_A2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[16].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[16].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9  { SS2BEG1 NR1BEG1 NN2BEG1 SR1BEG1 CLK_L1 CLBLL_LL_CLK }  FAN_ALT2 FAN_BOUNCE2 IMUX_L32 CLBLL_LL_C1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[17].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[17].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13  { SS2BEG1 NR1BEG1 NN2BEG1 SR1BEG1 CLK1 CLBLM_M_CLK }  WL1BEG0 IMUX_L18 CLBLL_LL_B2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[18].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[18].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C  { CLBLL_LOGIC_OUTS10 SS2BEG2 SE2BEG2 SS6BEG2 SL1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK1 CLBLM_M_CLK }  CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[19].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[19].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LL_CMUX CLBLL_LOGIC_OUTS22  { NR1BEG0 NE2BEG0 WR1BEG1 CLK_L1 CLBLL_LL_CLK }  IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[20].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[20].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C  { CLBLM_LOGIC_OUTS14 NN2BEG2 NE2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  CLBLM_M_CMUX CLBLM_LOGIC_OUTS22 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[21].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[21].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C  { CLBLM_LOGIC_OUTS14 SS2BEG2 SE6BEG2 SS2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  CLBLM_M_CMUX CLBLM_LOGIC_OUTS22 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[22].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[22].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C  { CLBLL_LOGIC_OUTS10 SS2BEG2 SS2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[23].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[23].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 BYP_ALT5 BYP_BOUNCE5  { FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  IMUX_L29 CLBLL_LL_C2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[24].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[24].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_C  { CLBLL_LOGIC_OUTS10 SS6BEG2 SS2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  CLBLL_L_CMUX CLBLL_LOGIC_OUTS18 IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[25].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[25].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 WL1BEG0  { NW2BEG1 EL1BEG0 SL1BEG0 ER1BEG1 CLK_L1 CLBLL_LL_CLK }  IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[26].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[26].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_L_B CLBLL_LOGIC_OUTS9  { BYP_ALT4 BYP_BOUNCE4 FAN_ALT1 FAN_BOUNCE1 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLL_L_CLK }  NR1BEG1 FAN_ALT6 FAN_BOUNCE6 IMUX_L41 CLBLL_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[27].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[27].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_L_BMUX CLBLM_LOGIC_OUTS17 SR1BEG_S0  { SE2BEG0 NR1BEG0 WR1BEG1 CLK0 CLBLM_L_CLK }  IMUX33 CLBLM_L_C1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[28].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[28].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C  { CLBLL_LL_CMUX CLBLL_LOGIC_OUTS22 NW2BEG0 SR1BEG_S0 ER1BEG1 CLK_L1 CLBLL_LL_CLK }  CLBLL_LOGIC_OUTS14 WL1BEG1 IMUX19 CLBLM_L_B2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[29].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[29].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 WL1BEG1  { SW2BEG1 NL1BEG1 EL1BEG0 ER1BEG1 CLK1 CLBLM_M_CLK }  IMUX_L3 CLBLL_L_A2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[30].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[30].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C  { CLBLM_LOGIC_OUTS10 SS6BEG2 SW2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  CLBLM_L_CMUX CLBLM_LOGIC_OUTS18 IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[31].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[31].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN6BEG2 EE4BEG2 NR1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLM_M_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[32].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[32].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_A  { CLBLM_LOGIC_OUTS12 NN2BEG0 NE2BEG0 WR1BEG1 CLK_L1 CLBLM_M_CLK }  CLBLM_M_AMUX CLBLM_LOGIC_OUTS20 IMUX_L20 CLBLM_L_C2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[33].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[33].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN6BEG2 EL1BEG1 EL1BEG0 ER1BEG1 CLK_L1 CLBLM_M_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[34].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[34].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NE6BEG2 SL1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLM_L_CLK }  SR1BEG3 IMUX_L40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[35].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[35].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_C CLBLL_LOGIC_OUTS14  { NN6BEG2 NL1BEG1 NL1BEG0 EE2BEG0 ER1BEG1 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX_L40 CLBLL_LL_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[36].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[36].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22  { SE2BEG0 NN6BEG0 WR1BEG1 CLK1 CLBLM_M_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[37].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[37].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { NN6BEG2 SR1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLM_L_CLK }  FAN_ALT5 FAN_BOUNCE5 IMUX_L41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[38].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[38].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9  { BYP_ALT4 BYP_BOUNCE4 BYP_ALT5 BYP_BOUNCE5 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  SS2BEG1 IMUX19 CLBLM_L_B2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[39].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[39].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C  { CLBLM_LOGIC_OUTS14 NN6BEG2 EL1BEG1 EL1BEG0 ER1BEG1 CLK_L0 CLBLM_L_CLK }  CLBLM_M_CMUX CLBLM_LOGIC_OUTS22 NL1BEG_N3 IMUX45 CLBLM_M_D2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[40].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[40].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NE6BEG2 NN6BEG2 NE2BEG2 SL1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLM_L_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[41].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[41].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NR1BEG2 NE2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLM_M_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[42].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[42].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NE6BEG2 NL1BEG1 NW2BEG1 SR1BEG1 CLK_L0 CLBLM_L_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[43].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[43].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NN2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[44].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[44].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 SR1BEG3  { WW2BEG3 WR1BEG1 CLK0 CLBLM_L_CLK }  IMUX_L40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[45].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[45].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10  { NN2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  FAN_ALT5 FAN_BOUNCE5 IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[46].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[46].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22  { NE6BEG0 WR1BEG1 CLK_L0 CLBLM_L_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[47].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[47].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_M_CMUX CLBLM_LOGIC_OUTS22  { NN2BEG0 FAN_ALT0 FAN_BOUNCE0 FAN_ALT5 FAN_BOUNCE5 CLK0 CLBLM_L_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[48].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[48].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_D CLBLM_LOGIC_OUTS15  { WW2BEG3 NN6BEG0 SR1BEG_S0 ER1BEG1 CLK_L1 CLBLM_M_CLK }  NL1BEG2 FAN_ALT7 FAN_BOUNCE7 IMUX2 CLBLM_M_A2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[49].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[49].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C  { CLBLM_L_CMUX CLBLM_LOGIC_OUTS18 ER1BEG1 CLK1 CLBLM_M_CLK }  CLBLM_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5 IMUX_L41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[50].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[50].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 EL1BEG1  { NE2BEG1 NL1BEG0 EE2BEG0 WR1BEG1 CLK_L1 CLBLM_M_CLK }  IMUX_L2 CLBLM_M_A2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[51].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[51].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_B CLBLM_LOGIC_OUTS9  { SR1BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLM_L_CLK }  FAN_ALT2 FAN_BOUNCE2 IMUX_L32 CLBLM_M_C1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[52].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[52].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_B CLBLM_LOGIC_OUTS13 SS2BEG1 NR1BEG1 NN2BEG1 SR1BEG1  { CLK_L1 CLBLM_M_CLK }  SW2BEG1 ER1BEG2 EL1BEG1 IMUX19 CLBLM_L_B2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[53].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[53].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13 BYP_ALT5 BYP_BOUNCE5  { FAN_ALT5 FAN_BOUNCE5 CLK_L1 CLBLL_LL_CLK }  IMUX_L29 CLBLL_LL_C2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[54].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[54].counter/clk"}]
set_property FIXED_ROUTE { { CLBLL_LL_B CLBLL_LOGIC_OUTS13  { SS2BEG1 ER1BEG2 SS2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK1 CLBLM_M_CLK }  NR1BEG1 NL1BEG0 IMUX_L32 CLBLL_LL_C1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[55].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[55].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { NL1BEG1 NN2BEG1 SR1BEG1 CLK1 CLBLM_M_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[56].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[56].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 NL1BEG1  { EL1BEG0 SL1BEG0 ER1BEG1 CLK_L1 CLBLL_LL_CLK }  FAN_ALT2 FAN_BOUNCE2 FAN_ALT3 FAN_BOUNCE3 IMUX_L19 CLBLM_L_B2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[57].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[57].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 NR1BEG2 NL1BEG1 NN2BEG1  { NE2BEG1 NW2BEG1 SR1BEG1 CLK_L1 CLBLM_M_CLK }  IMUX_L2 CLBLM_M_A2 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[58].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[58].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_L_CMUX CLBLM_LOGIC_OUTS18  { NN2BEG0 EE2BEG0 ER1BEG1 CLK_L0 CLBLM_L_CLK }  IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[59].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[59].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_LOGIC_OUTS10 FAN_ALT5 FAN_BOUNCE5  { CLK1 CLBLM_M_CLK }  IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[60].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[60].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_L_C CLBLM_L_CMUX CLBLM_LOGIC_OUTS18  { EE2BEG0 ER1BEG1 CLK_L1 CLBLM_M_CLK }  IMUX41 CLBLM_L_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[61].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[61].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14 SR1BEG3  { ER1BEG_S0 EE2BEG0 NE2BEG0 WR1BEG1 CLK_L0 CLBLM_L_CLK }  IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[62].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[62].counter/clk"}]
set_property FIXED_ROUTE { { CLBLM_M_C CLBLM_LOGIC_OUTS14  { SS6BEG2 SW2BEG2 FAN_ALT5 FAN_BOUNCE5 CLK_L0 CLBLL_L_CLK }  SR1BEG3 IMUX40 CLBLM_M_D1 }  } [get_nets -hierarchical -filter {NAME == "u_puf/ro[63].counter/clk"}]
set_property IS_ROUTE_FIXED true [get_nets -hierarchical -filter {NAME == "u_puf/ro[63].counter/clk"}]
