#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
manifest="${1:-$root_dir/manifests/verification_inputs_candidate.sha256}"
expected_files="$(mktemp)"
manifest_files="$(mktemp)"
trap 'rm -f "$expected_files" "$manifest_files"' EXIT

cd "$root_dir"
test -s "$manifest" || {
  echo "ERROR: verification-input manifest is missing: $manifest" >&2
  exit 1
}

if ! awk 'NF != 2 || length($1) != 64 || $1 !~ /^[0-9a-f]+$/ {bad=1}
          END {exit bad}' "$manifest"; then
  echo "ERROR: malformed SHA-256 manifest line" >&2
  exit 1
fi

# Lock only maintained inputs to the offline candidate gate. Generated build
# trees stay outside this set; the fuzzy C++ harness is generated by its
# Makefile and is therefore excluded explicitly below.
{
  printf '%s\n' Makefile
  find \
    sim/asic_frontend \
    sim/fips202 \
    sim/fuzzy_extractor \
    sim/kdf_kat \
    sim/kyber \
    sim/mlkem \
    sim/portability \
    sim/ro_puf \
    sim/system \
    -maxdepth 1 -type f \
    ! -path 'sim/fuzzy_extractor/tb_fuzzy_extractor_main.cpp' \
    \( -name Makefile -o -name '*.sv' -o -name '*.v' -o \
       -name '*.cpp' -o -name '*.c' -o -name '*.py' -o \
       -name '*.txt' \) -print
  find asic/filelists -maxdepth 1 -type f \
    \( -name '*.f' -o -name '*.txt' \) -print
  printf '%s\n' \
    scripts/check_asic_filelists.sh \
    scripts/check_asic_frontend.sh \
    scripts/check_asic_manifest.sh \
    scripts/check_asic_portability.sh \
    scripts/check_crypto_freeze.sh \
    scripts/check_standalone.sh
} | LC_ALL=C sort -u >"$expected_files"

awk '{print $2}' "$manifest" | LC_ALL=C sort >"$manifest_files"
if ! diff -u "$manifest_files" "$expected_files"; then
  echo "ERROR: verification-input file set differs from the candidate manifest" >&2
  exit 1
fi

sha256sum --check --strict "$manifest"
echo "PASS: verification harness/vector/oracle inputs and SHA-256 manifest match"
