# I4: create an isolated operational preservation project.  This script never
# opens or modifies the legacy SoC or characterization projects.
set_param general.maxThreads 1
set script_dir [file dirname [file normalize [info script]]]
set root_dir [file normalize [file join $script_dir ..]]
set build_dir [file join $root_dir build puf64_operational_preservation]
set project_name puf64_operational_zynq7020
set physical_prefix \
    {u_operational_uart/u_chain/u_puf64_core/u_puf64_physical/u_puf/}

file mkdir $build_dir

# Translate only placement and LUT pin locks from the exact qualified macro.
# Fixed routes are deliberately excluded; I4.3 decides whether routed DCP reuse
# is clean before any route can be locked.
proc i4_translate_physical_xdc {source output expected old_prefix new_prefix} {
    if {![file isfile $source]} { error "I4 golden constraint missing: $source" }
    set in_ch [open $source r]
    set data [read $in_ch]
    close $in_ch
    set occurrences [regexp -all -- [format {NAME == "%s} $old_prefix] $data]
    if {$occurrences != $expected} {
        error "I4 golden constraint cardinality mismatch: $source expected=$expected actual=$occurrences"
    }
    set translated [string map [list $old_prefix $new_prefix] $data]
    set out_ch [open $output w]
    puts $out_ch "## Generated by create_puf64_operational_project.tcl; do not freeze as a release artifact."
    puts -nonewline $out_ch $translated
    close $out_ch
}

set golden_place [file join $root_dir constraints puf_allpairs64_ripple_placement.xdc]
set golden_pins [file join $root_dir constraints puf_allpairs64_ripple_lockpins.xdc]
set scoped_place [file join $build_dir i4_puf64_scoped_placement.xdc]
set scoped_pins [file join $build_dir i4_puf64_scoped_lockpins.xdc]
i4_translate_physical_xdc $golden_place $scoped_place 2816 {u_puf/} $physical_prefix
i4_translate_physical_xdc $golden_pins $scoped_pins 256 {u_puf/} $physical_prefix

create_project $project_name $build_dir -part xc7z020clg400-2 -force
set_property target_language Verilog [current_project]
set_property simulator_language Mixed [current_project]

set sources [list \
    [file join $root_dir rtl common generic_bram.sv] \
    [file join $root_dir rtl common generic_fifo.sv] \
    [file join $root_dir rtl common generic_mult.sv] \
    [file join $root_dir rtl common generic_rom.sv] \
    [file join $root_dir rtl common generic_srl.sv] \
    [file join $root_dir rtl common generic_blk_mem_wrapper.sv] \
    [file join $root_dir rtl common generic_c_shift_ram_wrapper.sv] \
    [file join $root_dir rtl common generic_dist_mem_wrapper.sv] \
    [file join $root_dir rtl common keccak_pkg.sv] \
    [file join $root_dir rtl puf uart_rx.v] \
    [file join $root_dir rtl puf uart_tx.v] \
    [file join $root_dir rtl puf kp_ro_cell.sv] \
    [file join $root_dir rtl puf kp_ro_cell_xilinx.sv] \
    [file join $root_dir rtl debug kp_ripple_counter.sv] \
    [file join $root_dir rtl debug puf64_ro_bench.sv] \
    [file join $root_dir rtl puf kp_puf64_physical.sv] \
    [file join $root_dir rtl puf kp_puf64_mapping_scheduler.sv] \
    [file join $root_dir rtl top helper_record.sv] \
    [file join $root_dir rtl top edge_uart_transport.sv] \
    [file join $root_dir rtl top edge_root_binding.sv] \
    [file join $root_dir rtl top edge_puf64_operational_core.sv] \
    [file join $root_dir rtl top kdf_keccak_compact.sv] \
    [file join $root_dir rtl top edge_seed_controller.sv] \
    [file join $root_dir rtl top edge_kem_scrub_controller.sv] \
    [file join $root_dir rtl top edge_control_plane.sv] \
    [file join $root_dir rtl top edge_mlkem_core.sv] \
    [file join $root_dir rtl top edge_puf64_operational_chain.sv] \
    [file join $root_dir rtl top edge_puf64_operational_uart.sv] \
    [file join $root_dir rtl top edge_kcv_anchor.sv] \
    [file join $root_dir rtl top Edge_Puf64_Zynq_Operational_100MHz_Top.sv]]

foreach pattern [list \
        [file join $root_dir rtl hash_core *.v] \
        [file join $root_dir rtl kyber ref *.v] \
        [file join $root_dir rtl fuzzy_extractor *.v] \
        [file join $root_dir rtl fuzzy_extractor *.sv]] {
    foreach source [glob -nocomplain $pattern] { lappend sources $source }
}
foreach source $sources {
    if {![file isfile $source]} { error "I4 required RTL source missing: $source" }
}
add_files -norecurse $sources

set header_files [concat \
    [glob -nocomplain [file join $root_dir rtl top *.vh]] \
    [glob -nocomplain [file join $root_dir rtl fuzzy_extractor *.vh]]]
if {[llength $header_files] > 0} {
    add_files -norecurse $header_files
    set_property file_type {Verilog Header} [get_files $header_files]
}
set_property include_dirs [list \
    [file join $root_dir rtl top] \
    [file join $root_dir rtl common] \
    [file join $root_dir rtl hash_core] \
    [file join $root_dir rtl kyber ref] \
    [file join $root_dir rtl fuzzy_extractor]] [get_filesets sources_1]

set board_xdc [file join $root_dir constraints edge_puf64_zynq_operational_100mhz.xdc]
foreach constraint [list $board_xdc $scoped_place $scoped_pins] {
    if {![file isfile $constraint]} { error "I4 constraint missing: $constraint" }
}
add_files -fileset constrs_1 -norecurse [list $board_xdc $scoped_place $scoped_pins]
foreach constraint [list $scoped_place $scoped_pins] {
    set obj [get_files -quiet $constraint]
    set_property PROCESSING_ORDER LATE $obj
    set_property USED_IN_SYNTHESIS false $obj
    set_property USED_IN_IMPLEMENTATION true $obj
}

set_property top Edge_Puf64_Zynq_Operational_100MHz_Top [get_filesets sources_1]
set_property top_auto_set false [get_filesets sources_1]
update_compile_order -fileset sources_1
if {[llength [get_ips -quiet]] != 0 || [llength [get_files -all -quiet *.xci]] != 0} {
    error "Generated Xilinx IP unexpectedly entered the I4 project"
}
puts "I4_OPERATIONAL_PROJECT=[file join $build_dir ${project_name}.xpr]"
puts "I4_PHYSICAL_PREFIX=$physical_prefix"
puts "I4_FIXED_ROUTE=0"
puts "I4_ANCHOR=PUBLIC_BUILD_TOKEN_NONRELEASE"
close_project
