# I4.3 — Reuse physical macro (run only if I4.2 fingerprint mismatches on routes).
# Order: A (scoped routed-macro import) first, then B (placement + LOCK_PINS).
# This template is intentionally NOT wired into the default build; enabling it
# requires an explicit operator decision per candidate.
#
# Option A sketch (Vivado 2020.1, Tcl):
#   # 1. Open the golden routed DCP read-only, write a scoped checkpoint of
#   #    ONLY the u_puf macro (no system clock / control / telemetry logic).
#   # 2. In the operational run, after place_design, scoped-import it under
#   #    u_operational_uart/u_chain/u_puf64_core/u_puf64_physical/u_puf.
#   # 3. Keep internal macro placement+routing; leave control/reset/telemetry
#   #    and system-clock routes unfixed outside the macro.
#   # 4. Verify every macro port still has a valid connection.
#   # Abort the candidate on ANY partial route, RTSTAT or route conflict.
#   # Never force FIXED_ROUTE to silence the router.
#
# Option B (fallback): apply the 1408 LOC/BEL + 256 LOCK_PINS from the scoped
# XDCs generated by create_puf64_operational_project.tcl, let the router run
# free, re-extract the candidate fingerprint and compare.  A route mismatch is
# I4_PHYSICAL_FINGERPRINT_MISMATCH; the new candidate needs full train/holdout
# re-qualification and must not go straight to the operational board test.
puts "I4.3 template loaded (no-op). Enable explicitly per candidate."
