/* AUTO-GENERATED by scripts/helper_record_spec.py --emit. Do not edit. */
#ifndef HELPER_RECORD_SPEC_H
#define HELPER_RECORD_SPEC_H

#define HREC_MAGIC            0x55464b52u
#define HREC_RECORD_VERSION   0x01u
#define HREC_PROTOCOL_VERSION 0x01u
#define HREC_BYTES            76u
#define HREC_HELPER_BYTES     33u
#define HREC_KCV_BYTES        28u

#define HREC_OFF_MAGIC            0u
#define HREC_OFF_RECORD_VERSION   4u
#define HREC_OFF_PROTOCOL_VERSION 5u
#define HREC_OFF_PROFILE          6u
#define HREC_OFF_FE_PARAM         7u
#define HREC_OFF_MAPPING_LEN      8u
#define HREC_OFF_MAPPING_TAG      9u
#define HREC_OFF_GENERATION       11u
#define HREC_OFF_RESERVED         12u
#define HREC_OFF_HELPER           13u
#define HREC_OFF_KCV              46u
#define HREC_OFF_CRC              74u

#define HREC_OK                  0u
#define HREC_ERR_MAGIC           1u
#define HREC_ERR_RECORD_VERSION  2u
#define HREC_ERR_PROTOCOL_VERSION 3u
#define HREC_ERR_PROFILE         4u
#define HREC_ERR_FE_PARAM        5u
#define HREC_ERR_MAPPING         6u
#define HREC_ERR_RESERVED        7u
#define HREC_ERR_CRC             8u
#define HREC_ERR_LENGTH          9u

#endif
