// AUTO-GENERATED by scripts/helper_record_spec.py --emit. Do not edit.
// No include guard: localparams are module scoped and each module that
// needs them includes this file exactly once.

localparam [31:0] HREC_MAGIC            = 32'h55464b52;
localparam [7:0]  HREC_RECORD_VERSION   = 8'h02;
localparam [7:0]  HREC_PROTOCOL_VERSION = 8'h01;
localparam integer HREC_BYTES          = 76;
localparam integer HREC_HELPER_BYTES   = 33;
localparam integer HREC_KCV_BYTES      = 28;
localparam integer HREC_OFF_RECORD_VERSION   = 4;
localparam integer HREC_OFF_PROTOCOL_VERSION = 5;
localparam integer HREC_OFF_PROFILE          = 6;
localparam integer HREC_OFF_FE_PARAM         = 7;
localparam integer HREC_OFF_MAPPING_LEN_BYTES = 8;
localparam integer HREC_OFF_MAPPING_TAG      = 9;
localparam integer HREC_OFF_GENERATION       = 11;
localparam integer HREC_OFF_RESERVED         = 12;
localparam integer HREC_OFF_HELPER           = 13;
localparam integer HREC_OFF_KCV              = 46;
localparam integer HREC_OFF_CRC              = 74;
localparam [3:0]  HREC_OK               = 4'd0;
localparam [3:0]  HREC_ERR_MAGIC        = 4'd1;
localparam [3:0]  HREC_ERR_RECORD_VER   = 4'd2;
localparam [3:0]  HREC_ERR_PROTOCOL_VER = 4'd3;
localparam [3:0]  HREC_ERR_PROFILE      = 4'd4;
localparam [3:0]  HREC_ERR_FE_PARAM     = 4'd5;
localparam [3:0]  HREC_ERR_MAPPING      = 4'd6;
localparam [3:0]  HREC_ERR_RESERVED     = 4'd7;
localparam [3:0]  HREC_ERR_CRC          = 4'd8;
localparam [3:0]  HREC_ERR_LENGTH       = 4'd9;

// CRC-16/CCITT-FALSE over bytes 0..HREC_OFF_CRC-1.
// hrec_crc16_step is the synthesizable per-byte form: the transport
// advances one byte per received/sent UART byte, so the datapath never
// contains a 592-stage combinational cone (security review finding).
// hrec_crc16 is a test/reference-only convenience and MUST NOT be used
// on a synthesizable datapath.
function automatic [15:0] hrec_crc16_step;
    input [15:0] crc;
    input [7:0]  din;
    integer m;
    reg [15:0] c;
    begin
        c = crc ^ {din, 8'h00};
        for (m = 0; m < 8; m = m + 1) begin
            if (c[15])
                c = {c[14:0], 1'b0} ^ 16'h1021;
            else
                c = {c[14:0], 1'b0};
        end
        hrec_crc16_step = c;
    end
endfunction

function automatic [15:0] hrec_crc16;
    input [8*HREC_BYTES-1:0] raw;
    integer k;
    integer m;
    reg [15:0] crc;
    begin
        crc = 16'hFFFF;
        for (k = 0; k < HREC_OFF_CRC; k = k + 1) begin
            crc = crc ^ {raw[8*k +: 8], 8'h00};
            for (m = 0; m < 8; m = m + 1) begin
                if (crc[15])
                    crc = {crc[14:0], 1'b0} ^ 16'h1021;
                else
                    crc = {crc[14:0], 1'b0};
            end
        end
        hrec_crc16 = crc;
    end
endfunction
