// AUTO-GENERATED by host/puf64_generate_mapping.py --emit. Do not edit.
// Mapping bit convention (frozen, audited):
//   pair j = ordered_pairs[j] = (a,b), 0 <= a < b < 64.
//   response bit j = 1 if count_a < count_b, 0 if count_a > count_b.
//   count_a == count_b is a tie: INVALID, fail-closed in operation.
//   FE vector packs LSB-first: bit j -> byte j/8, bit j%8.
localparam integer PUF64_MAP_LEN_BITS   = 264;
localparam integer PUF64_MAP_LEN_BYTES  = 33;
localparam integer PUF64_MAP_PAIR_COUNT = 264;
localparam [15:0]  PUF64_MAP_TAG        = 16'hd501;
localparam [255:0] PUF64_MAP_DIGEST_SHA3_256 = 256'h01d5d3a77d19c54d4bfb7a71844edd5627b8fa7def775ae82d911a7a706d5858;
localparam [255:0] PUF64_MAP_SELECTION_SHA256 = 256'h299a089d8493058047ff830921c169b9dafda93b0066ab8ef20c67f8b39afa11;
// {a[5:0], b[5:0]} per pair, pair 0 at the most significant end.
localparam [3167:0] PUF64_MAP_PAIRS = 3168'h122afa317453063d3d6e8a71290621b7bbaf1ac15c0e0d7c2362e49b93f86bf0997a77705251ce7ea03e2735b237749512b8ba3134578f407d6f1a294182a1b6fbbb16c19c83c0f52f6224e393e665a0bf75e9f01d43a502a7fecb32563554b71174fa32246b6f48e8c7d0692bb42d62f86e0ec73c1a01759b62399382cf69e6670b077f52a0251df3becf724d5564b21135fa32b462a3d05b8f1a742af63b42e86d22c0dc1601b5dbc9262f96b83d909e9ff7655303aa00725fcfe5b73721154ba06b8b432347d5e84f129b62942c1ad16e72183bbf50f693c7b920f2da0a69f865d53f3b07e51f30095aa37e132dfa315452af40625f14e82a363d6eda6e86c41c82fd7b1b60e41793fc21a08b9a77785193bf79f0309731d636a4be109cba337455a2b5f48b10536232bd6eea6db3b42072f8751761a40f96bc0882e73de7665383997ffc335a50321cd4aa57e13727a33d8a8af10574634f461b2a916db2f1ae73b821435db8e7c93f0cf6a62272dd0a551e65f24e5b0037ab31d2cbe10d57a31b2ab6224694345ed061;
// Sorted canonical-sweep lookup: (full_pair_index[10:0], dest[7:0]).
localparam [2903:0] PUF64_MAP_SORTED_FULL = 2904'h00c0201202905e0c41b03d0a01502c05e0be180330680f42084289313027c500aa172314690d61b4388758ec1de3e87f10420c4208991c2464a0a394b2ae560ac9602c2590c0184310640c8992332668d49aa35c6c0d91bb39e788f69f73f47fd04a0c42c85d0fa2847890d272594be98533a694da9e53da81518a3d4b299550aad5c2ba578b0163ac85a0b71712ec602c2587315642cb59933868cd1da8b566bcdc1ba37f706e1dc9b9472ae6dce3a7750ea9d63b7770ef9e03d27aefb1fa3f97f90020b41f8450a21943787d10e24c518b11663ec8192325a4e49e9472f260cc599133a6b4dc9bb37a724ea9ed3e27dcfea014229252ca7d50aa2d52aaf562add5eadd5f2c4589b1b652cad9fb4f6bad7db7b93756ed5eebdf7c2ff60ac178670d61bc458cb1de3ec8993b2be5accf9e73ee80d1da6f556add79b1365eccd9db83736e7dd5bb780f13e2dc7392730e6dd0ba3f53ebbdabc1785f19e43caf9cf4debbd7fb4f71efbe27cd;
localparam [2375:0] PUF64_MAP_SORTED_DEST = 2376'h3d26cb23a5cb6df61b62b90cb07518108e8112b4966153abd928561abc8da0e579305e8f682f9fe603f90000204f37c1a6e163a5164f672c05a4e6783114eb37ab9b8197e8e1765a4d24964317a1b020512ebe47a7b0e380108714a99d102341218e5349bd422d3181c844a001404848331301c23e5e1f83c9d6b8e4f2982dadce8d41984d622855b2d124935415dca101b04466372c1086840fb74be3f402f54a86731056cf70c160f0d64b97a00de6d271f41d3ea160ca461985ce0981b19104a34a9c68967c154a8f339b442806543204c4446331d84d1b1ddaa175a95d701648a64343b6c3b5588d172a8d64b66b89888210914cc243894920f15d2d0a0121ba54ec276119192a90399df8e351005d4ca15028162b473648c3c5fbf8b87c02ab41eef3827c64f0;
function automatic [10:0] puf64_map_sorted_full(input integer j);
    puf64_map_sorted_full = PUF64_MAP_SORTED_FULL[2904-1 - 11*j -: 11];
endfunction
function automatic [8:0] puf64_map_sorted_dest(input integer j);
    puf64_map_sorted_dest = PUF64_MAP_SORTED_DEST[2376-1 - 9*j -: 9];
endfunction
function automatic [5:0] puf64_map_pair_a(input integer j);
    puf64_map_pair_a = PUF64_MAP_PAIRS[3168-1 - 12*j -: 6];
endfunction
function automatic [5:0] puf64_map_pair_b(input integer j);
    puf64_map_pair_b = PUF64_MAP_PAIRS[3168-1 - 12*j - 6 -: 6];
endfunction
