// AUTO-GENERATED by host/puf64_generate_mapping.py --emit. Do not edit.
// Mapping bit convention (frozen, audited):
//   pair j = ordered_pairs[j] = (a,b), 0 <= a < b < 64.
//   response bit j = 1 if count_a < count_b, 0 if count_a > count_b.
//   count_a == count_b is a tie: INVALID, fail-closed in operation.
//   FE vector packs LSB-first: bit j -> byte j/8, bit j%8.
localparam integer PUF64_MAP_LEN_BITS   = 264;
localparam integer PUF64_MAP_LEN_BYTES  = 33;
localparam integer PUF64_MAP_PAIR_COUNT = 264;
localparam [15:0]  PUF64_MAP_TAG        = 16'hd501;
localparam [255:0] PUF64_MAP_DIGEST_SHA3_256 = 256'h01d5d3a77d19c54d4bfb7a71844edd5627b8fa7def775ae82d911a7a706d5858;
localparam [255:0] PUF64_MAP_SELECTION_SHA256 = 256'h299a089d8493058047ff830921c169b9dafda93b0066ab8ef20c67f8b39afa11;
// {a[5:0], b[5:0]} per pair, pair 0 at the most significant end.
localparam [3167:0] PUF64_MAP_PAIRS = 3168'h122afa317453063d3d6e8a71290621b7bbaf1ac15c0e0d7c2362e49b93f86bf0997a77705251ce7ea03e2735b237749512b8ba3134578f407d6f1a294182a1b6fbbb16c19c83c0f52f6224e393e665a0bf75e9f01d43a502a7fecb32563554b71174fa32246b6f48e8c7d0692bb42d62f86e0ec73c1a01759b62399382cf69e6670b077f52a0251df3becf724d5564b21135fa32b462a3d05b8f1a742af63b42e86d22c0dc1601b5dbc9262f96b83d909e9ff7655303aa00725fcfe5b73721154ba06b8b432347d5e84f129b62942c1ad16e72183bbf50f693c7b920f2da0a69f865d53f3b07e51f30095aa37e132dfa315452af40625f14e82a363d6eda6e86c41c82fd7b1b60e41793fc21a08b9a77785193bf79f0309731d636a4be109cba337455a2b5f48b10536232bd6eea6db3b42072f8751761a40f96bc0882e73de7665383997ffc335a50321cd4aa57e13727a33d8a8af10574634f461b2a916db2f1ae73b821435db8e7c93f0cf6a62272dd0a551e65f24e5b0037ab31d2cbe10d57a31b2ab6224694345ed061;
function automatic [5:0] puf64_map_pair_a(input integer j);
    puf64_map_pair_a = PUF64_MAP_PAIRS[3168-1 - 12*j -: 6];
endfunction
function automatic [5:0] puf64_map_pair_b(input integer j);
    puf64_map_pair_b = PUF64_MAP_PAIRS[3168-1 - 12*j - 6 -: 6];
endfunction
